services:
  - type: web
    name: ai-chatbot
    env: node
    plan: free
    buildCommand: cd Frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 5001
      - key: HF_TOKEN
        sync: false
      - key: HF_API_KEY
        sync: false
